import { lazy, type ComponentType, type LazyExoticComponent } from 'react';
import {
  Activity,
  Binary,
  Blocks,
  Bomb,
  BookOpen,
  Braces,
  Calculator,
  CalendarDays,
  Camera,
  ClipboardList,
  Clock,
  CloudSun,
  Code,
  Cpu,
  Dices,
  Disc3,
  FileText,
  Film,
  FolderTree,
  Gamepad2,
  Globe,
  Grid2x2,
  Grid3x3,
  HardDrive,
  Image as ImageIcon,
  Keyboard,
  Music2,
  Paintbrush,
  Palette,
  Regex,
  Ruler,
  Settings,
  Sparkles,
  StickyNote,
  Terminal,
} from 'lucide-react';
import type { AppMeta, AppProps } from '@/shell/types';

/**
 * 预扫描所有应用目录。Vite 会在构建时为每个匹配文件生成独立 chunk，
 * 点击应用时才真正下载对应代码，避免首屏一次性拉进全部应用。
 */
const modules = import.meta.glob<{ default: ComponentType<AppProps> }>(
  './*/index.tsx',
);

/** 应用 id → 入口文件路径 */
const ENTRY: Record<string, string> = {
  terminal: './Terminal/index.tsx',
  files: './FileManager/index.tsx',
  notepad: './Notepad/index.tsx',
  calculator: './Calculator/index.tsx',
  settings: './Settings/index.tsx',
  browser: './Browser/index.tsx',
  'deep-ai': './Deep AI/index.tsx',
  bilibili: './Bilibili/index.tsx',
  music: './MusicPlayer/index.tsx',
  gallery: './Gallery/index.tsx',
  minesweeper: './Minesweeper/index.tsx',
  game2048: './Game2048/index.tsx',
  video: './VideoPlayer/index.tsx',
  netease: './NeteaseMusic/index.tsx',

  /* ---------- 开发 ---------- */
  markdown: './MarkdownPreview/index.tsx',
  'json-tool': './JsonTool/index.tsx',
  base64: './Base64Tool/index.tsx',
  regex: './RegexTester/index.tsx',
  'color-tool': './ColorTool/index.tsx',

  /* ---------- 工具 ---------- */
  'unit-converter': './UnitConverter/index.tsx',
  random: './RandomTool/index.tsx',
  'sticky-notes': './StickyNotes/index.tsx',
  paint: './Paint/index.tsx',
  typing: './TypingTest/index.tsx',

  /* ---------- 系统 ---------- */
  help: './Help/index.tsx',
  clock: './Clock/index.tsx',
  calendar: './Calendar/index.tsx',
  'task-manager': './TaskManager/index.tsx',
  sysmon: './SystemMonitor/index.tsx',
  disk: './DiskUsage/index.tsx',
  clipboard: './ClipboardHistory/index.tsx',

  /* ---------- 影音 / 网络 ---------- */
  camera: './Camera/index.tsx',
  weather: './Weather/index.tsx',

  /* ---------- 游戏 ---------- */
  snake: './Snake/index.tsx',
  tetris: './Tetris/index.tsx',
  gomoku: './Gomoku/index.tsx',
};

export const CATEGORIES = [
  '全部',
  '系统',
  '工具',
  '开发',
  '网络',
  '影音',
  '游戏',
] as const;

export const APPS: AppMeta[] = [
  {
    id: 'terminal',
    name: '终端',
    icon: Terminal,
    category: '系统',
    description: '模拟 Shell，支持 ls / cd / cat / echo 等命令',
    defaultWidth: 720,
    defaultHeight: 440,
    accent: '#4ec9b0',
  },
  {
    id: 'files',
    name: '文件管理器',
    icon: FolderTree,
    category: '系统',
    description: '浏览与编辑虚拟文件系统中的文件',
    defaultWidth: 860,
    defaultHeight: 560,
    accent: '#1793d1',
  },
  {
    id: 'notepad',
    name: '记事本',
    icon: FileText,
    category: '工具',
    description: '纯文本编辑，内容持久化到虚拟磁盘',
    defaultWidth: 640,
    defaultHeight: 480,
    accent: '#e5c07b',
  },
  {
    id: 'calculator',
    name: '计算器',
    icon: Calculator,
    category: '工具',
    description: '四则运算与常用函数',
    defaultWidth: 320,
    defaultHeight: 440,
    minWidth: 280,
    minHeight: 400,
    accent: '#c678dd',
    singleton: true,
  },
  {
    id: 'settings',
    name: '设置',
    icon: Settings,
    category: '系统',
    description: '壁纸、窗口透明度、自动锁屏',
    defaultWidth: 620,
    defaultHeight: 520,
    accent: '#7d8496',
    singleton: true,
  },
  {
    id: 'browser',
    name: '浏览器',
    icon: Globe,
    category: '网络',
    description: '沙箱 iframe 的内嵌网页浏览',
    defaultWidth: 960,
    defaultHeight: 640,
    accent: '#61afef',
  },
  {
    id: 'deep-ai',
    name: 'AI 助手',
    icon: Sparkles,
    category: '工具',
    description: '自定义 API / Agent，轻量、简洁的个人 AI 助手',
    defaultWidth: 980,
    defaultHeight: 680,
    minWidth: 700,
    minHeight: 420,
    accent: '#61afef',
  },
  {
    id: 'bilibili',
    name: '哔哩哔哩',
    icon: Film,
    category: '影音',
    description: '二维码登录 · 视频播放 · 评论与弹幕展示',
    defaultWidth: 1180,
    defaultHeight: 760,
    minWidth: 980,
    minHeight: 560,
    accent: '#f43f5e',
  },
  {
    id: 'music',
    name: '音乐',
    icon: Music2,
    category: '影音',
    description: '本地音频播放 · 队列 · 媒体键控制',
    defaultWidth: 720,
    defaultHeight: 520,
    accent: '#e06c75',
    // 全局媒体桥 + 同一份 playlist.json，多开会互相打架
    singleton: true,
  },
  {
    id: 'gallery',
    name: '画廊',
    icon: ImageIcon,
    category: '工具',
    description: '浏览虚拟磁盘里保存的图片',
    defaultWidth: 760,
    defaultHeight: 540,
    accent: '#56b6c2',
  },
  {
    id: 'minesweeper',
    name: '扫雷',
    icon: Bomb,
    category: '游戏',
    description: '经典扫雷，支持三种难度',
    defaultWidth: 380,
    defaultHeight: 480,
    minWidth: 340,
    minHeight: 440,
    accent: '#d19a66',
    singleton: true,
  },
  {
    id: 'game2048',
    name: '2048',
    icon: Grid3x3,
    category: '游戏',
    description: '合并数字，挑战 2048',
    defaultWidth: 380,
    defaultHeight: 540,
    minWidth: 320,
    minHeight: 460,
    accent: '#c678dd',
    singleton: true,
  },
  {
    id: 'video',
    name: '视频',
    icon: Film,
    category: '影音',
    description: '本地视频与在线 URL，含 m3u8 / HLS 自动加载',
    defaultWidth: 880,
    defaultHeight: 560,
    minWidth: 560,
    minHeight: 380,
    accent: '#be5046',
  },
  {
    id: 'netease',
    name: '在线音乐',
    icon: Disc3,
    category: '影音',
    description: '搜索 / 播放 网易 / QQ / 酷我等音源',
    defaultWidth: 880,
    defaultHeight: 600,
    minWidth: 720,
    minHeight: 500,
    accent: '#e84393',
  },

  /* ============================ 开发 ============================ */
  {
    id: 'markdown',
    name: 'Markdown 预览',
    icon: Code,
    category: '开发',
    description: '边写边看，支持标题/列表/代码块/表格，可存进虚拟磁盘',
    defaultWidth: 920,
    defaultHeight: 620,
    minWidth: 520,
    minHeight: 360,
    accent: '#61afef',
  },
  {
    id: 'json-tool',
    name: 'JSON 工具',
    icon: Braces,
    category: '开发',
    description: '格式化 / 压缩 / 校验定位行列 / 转 TS 接口 / 统计',
    defaultWidth: 900,
    defaultHeight: 620,
    minWidth: 520,
    minHeight: 380,
    accent: '#e5c07b',
  },
  {
    id: 'base64',
    name: '编解码工具',
    icon: Binary,
    category: '开发',
    description: 'Base64 / URL / HTML 实体互转，中文不乱码',
    defaultWidth: 840,
    defaultHeight: 580,
    minWidth: 480,
    minHeight: 340,
    accent: '#56b6c2',
  },
  {
    id: 'regex',
    name: '正则测试',
    icon: Regex,
    category: '开发',
    description: '实时高亮匹配、捕获组、替换预览、常用正则速查',
    defaultWidth: 920,
    defaultHeight: 640,
    minWidth: 560,
    minHeight: 400,
    accent: '#c678dd',
  },
  {
    id: 'color-tool',
    name: '颜色工具',
    icon: Palette,
    category: '开发',
    description: 'HEX/RGB/HSL 互转、明暗阶梯、配色方案、对比度检测',
    defaultWidth: 880,
    defaultHeight: 620,
    minWidth: 520,
    minHeight: 380,
    accent: '#e84393',
  },

  /* ============================ 工具 ============================ */
  {
    id: 'unit-converter',
    name: '单位换算',
    icon: Ruler,
    category: '工具',
    description: '长度 / 质量 / 温度 / 面积 / 体积 / 速度 / 数据 等 10 类',
    defaultWidth: 800,
    defaultHeight: 580,
    minWidth: 480,
    minHeight: 360,
    accent: '#98c379',
  },
  {
    id: 'random',
    name: '随机生成',
    icon: Dices,
    category: '工具',
    description: '随机数 / 密码 / UUID / 抽签 / 掷骰 / 随机配色',
    defaultWidth: 780,
    defaultHeight: 580,
    minWidth: 460,
    minHeight: 360,
    accent: '#c678dd',
  },
  {
    id: 'sticky-notes',
    name: '便签',
    icon: StickyNote,
    category: '工具',
    description: '多张便签，改完自动落盘到 /home/arch/notes/',
    defaultWidth: 840,
    defaultHeight: 580,
    minWidth: 520,
    minHeight: 360,
    accent: '#e5c07b',
  },
  {
    id: 'paint',
    name: '画图',
    icon: Paintbrush,
    category: '工具',
    description: '画笔 / 形状 / 油漆桶 / 吸管 / 撤销重做 / 导出 PNG',
    defaultWidth: 920,
    defaultHeight: 660,
    minWidth: 560,
    minHeight: 420,
    accent: '#e84393',
  },
  {
    id: 'typing',
    name: '打字练习',
    icon: Keyboard,
    category: '工具',
    description: '中英文打字，实时 WPM 与准确率，保留历史成绩',
    defaultWidth: 900,
    defaultHeight: 600,
    minWidth: 520,
    minHeight: 380,
    accent: '#98c379',
  },

  /* ============================ 系统 ============================ */
  {
    id: 'help',
    name: '帮助手册',
    icon: BookOpen,
    category: '系统',
    description: '应用清单、快捷键、终端命令速查、常见问题',
    defaultWidth: 900,
    defaultHeight: 640,
    minWidth: 560,
    minHeight: 400,
    accent: '#7d8496',
  },
  {
    id: 'clock',
    name: '时钟',
    icon: Clock,
    category: '系统',
    description: '时钟 / 世界时区 / 秒表 / 倒计时 / 番茄钟',
    defaultWidth: 760,
    defaultHeight: 580,
    minWidth: 460,
    minHeight: 380,
    accent: '#d19a66',
  },
  {
    id: 'calendar',
    name: '日历',
    icon: CalendarDays,
    category: '系统',
    description: '月视图与事件，支持新增 / 编辑 / 删除',
    defaultWidth: 880,
    defaultHeight: 620,
    minWidth: 560,
    minHeight: 400,
    accent: '#e06c75',
  },
  {
    id: 'task-manager',
    name: '任务管理器',
    icon: Activity,
    category: '系统',
    description: '窗口即进程：可结束 / 聚焦 / 看资源占用与 FPS',
    defaultWidth: 940,
    defaultHeight: 640,
    minWidth: 600,
    minHeight: 400,
    accent: '#e06c75',
    singleton: true,
  },
  {
    id: 'sysmon',
    name: '系统监视器',
    icon: Cpu,
    category: '系统',
    description: 'FPS / 内存 / 事件循环延迟实时曲线，存储配额',
    defaultWidth: 880,
    defaultHeight: 620,
    minWidth: 560,
    minHeight: 400,
    accent: '#4ec9b0',
    singleton: true,
  },
  {
    id: 'disk',
    name: '存储分析',
    icon: HardDrive,
    category: '系统',
    description: '目录占用、大文件排行、备份导出与恢复',
    defaultWidth: 940,
    defaultHeight: 660,
    minWidth: 600,
    minHeight: 420,
    accent: '#1793d1',
  },
  {
    id: 'clipboard',
    name: '剪贴板历史',
    icon: ClipboardList,
    category: '系统',
    description: '历史记录、置顶、搜索，可选监听系统剪贴板',
    defaultWidth: 800,
    defaultHeight: 580,
    minWidth: 480,
    minHeight: 360,
    accent: '#56b6c2',
    singleton: true,
  },

  /* ========================= 影音 / 网络 ========================= */
  {
    id: 'camera',
    name: '相机',
    icon: Camera,
    category: '影音',
    description: '摄像头拍照与录像，需要授权',
    defaultWidth: 900,
    defaultHeight: 660,
    minWidth: 560,
    minHeight: 420,
    accent: '#61afef',
    singleton: true,
  },
  {
    id: 'weather',
    name: '天气',
    icon: CloudSun,
    category: '网络',
    description: 'Open-Meteo 实时天气与 7 天预报（无需 API Key）',
    defaultWidth: 900,
    defaultHeight: 640,
    minWidth: 560,
    minHeight: 400,
    accent: '#61afef',
  },

  /* ============================ 游戏 ============================ */
  {
    id: 'snake',
    name: '贪吃蛇',
    icon: Gamepad2,
    category: '游戏',
    description: '方向键操作，三档速度，最高分本地保存',
    defaultWidth: 560,
    defaultHeight: 640,
    minWidth: 440,
    minHeight: 520,
    accent: '#4ec9b0',
    singleton: true,
  },
  {
    id: 'tetris',
    name: '俄罗斯方块',
    icon: Blocks,
    category: '游戏',
    description: '含 Next / Hold / 等级加速与计分规则',
    defaultWidth: 600,
    defaultHeight: 700,
    minWidth: 480,
    minHeight: 580,
    accent: '#61afef',
    singleton: true,
  },
  {
    id: 'gomoku',
    name: '五子棋',
    icon: Grid2x2,
    category: '游戏',
    description: '15×15 棋盘，三档 AI 难度，可撤销',
    defaultWidth: 700,
    defaultHeight: 720,
    minWidth: 540,
    minHeight: 600,
    accent: '#d19a66',
    singleton: true,
  },
];

const cache = new Map<string, LazyExoticComponent<ComponentType<AppProps>>>();

/** 取得应用的懒加载组件，同一应用只创建一次 lazy 包装 */
export function loadApp(id: string) {
  const cached = cache.get(id);
  if (cached) return cached;

  const entry = ENTRY[id];
  const loader = entry ? modules[entry] : undefined;
  if (!loader) {
    throw new Error(`应用 ${id} 未注册，找不到入口 ${entry ?? '(未知)'}`);
  }

  const Comp = lazy(loader);
  cache.set(id, Comp);
  return Comp;
}

export function getApp(id: string): AppMeta | undefined {
  return APPS.find((a) => a.id === id);
}

/** 校验注册表与磁盘目录是否一一对应，供开发期自检 */
export function auditRegistry(): string[] {
  const problems: string[] = [];
  for (const [id, entry] of Object.entries(ENTRY)) {
    if (!modules[entry]) problems.push(`${id}: 缺少文件 ${entry}`);
    if (!APPS.some((a) => a.id === id)) problems.push(`${id}: 缺少元数据`);
  }
  for (const path of Object.keys(modules)) {
    if (!Object.values(ENTRY).includes(path)) {
      problems.push(`孤儿应用目录: ${path}`);
    }
  }
  return problems;
}
